use_frameworks!
workspace '../BLECentralManager'

target 'BLECentralManager_iOS_Example' do
  platform :ios, '9.0'
  project 'BLECentralManager_iOS'
  pod 'BLECentralManager', :path => '../'

  target 'BLECentralManager_iOS_Tests' do
    inherit! :search_paths

  end
end

target :'BLECentralManager_Mac_Example' do
  platform :osx, '10.11'
  project 'BLECentralManager_Mac'
  pod 'BLECentralManager', :path => '../'
  target 'BLECentralManager_Mac_Tests' do
    inherit! :search_paths
  end
end
