use_frameworks!
workspace '../BLECentralManager'

target 'BLECentralManager_Example' do
  platform :ios, '9.0'
  project 'BLECentralManager'
  pod 'BLECentralManager', :path => '../'

  target 'BLECentralManager_Tests' do
    inherit! :search_paths

  end
end
