# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c

# cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Examples

script:
  - export LC_ALL=en_US.UTF-8
  - set -o pipefail && xcodebuild -workspace BLECentralManager.xcworkspace -scheme BLECentralManager_iOS_Swift -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild -workspace BLECentralManager.xcworkspace -scheme BLECentralManager_Mac_Swift | xcpretty
  - set -o pipefail && xcodebuild -workspace BLECentralManager.xcworkspace -scheme BLECentralManager_iOS_ObjC -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && xcodebuild -workspace BLECentralManager.xcworkspace -scheme BLECentralManager_Mac_ObjC | xcpretty
  - xcodebuild -project Examples/Peripheral_Example.xcodeproj -scheme Peripheral_Example | xcpretty
  - pod lib lint
