use_frameworks!
workspace '../BLECentralManager'

target 'BLECentralManager_iOS_ObjC' do
  platform :ios, '9.0'
  project 'BLECentralManager_iOS_ObjC'
  pod 'BLECentralManager/ObjC', :path => '../'
end

target 'BLECentralManager_iOS_Swift' do
  platform :ios, '9.0'
  project 'BLECentralManager_iOS_Swift'
  pod 'BLECentralManager/Swift', :path => '../'
end

target :'BLECentralManager_Mac_ObjC' do
  platform :osx, '10.11'
  project 'BLECentralManager_Mac_ObjC'
  pod 'BLECentralManager/ObjC', :path => '../'
end

target :'BLECentralManager_Mac_Swift' do
  platform :osx, '10.11'
  project 'BLECentralManager_Mac_Swift'
  pod 'BLECentralManager/Swift', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name.end_with?('_Swift')
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D DEBUG'
                end
            end
        end
    end
end
